FROM ubuntu:16.04
ADD lang_detector_server lang_detector_server
RUN apt-get update
RUN apt-get install -y software-properties-common
RUN add-apt-repository "deb http://security.ubuntu.com/ubuntu xenial-security main"
RUN apt-get update
RUN apt-get install -y libicu55
WORKDIR /lang_detector_server
CMD ["/lang_detector_server/lang_detector_server", "--port", "9999"]
ENV LANG C.UTF-8

